[package]
name = "idcdump"
version = "1.0.0"
authors = ["Cos8o <help.ps.cos8o@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
structopt = "0.3"